# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-01-11 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.IntegerField()),
                ('Number', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
